"""Criar tabela routes

Revision ID: 285dfa752773
Revises: 
Create Date: 2025-07-12 19:02:08.871613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '285dfa752773'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modo', sa.String(length=20), nullable=False),
    sa.Column('distancia_total', sa.Float(), nullable=False),
    sa.Column('duracao_total', sa.Float(), nullable=False),
    sa.Column('enderecos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criada_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    # ### end Alembic commands ###
